graph TB
    subgraph "DATA & UTILS"
        DataJS[data.js<br/>cards, reviews, text, icons]
        Utils[utils.js<br/>build, buildBlock, createSvgIcon, buildIconButton]
    end

    subgraph "SERVICES"
        Storage[storageService.js<br/>getUser, saveUser, getSession, pushSession, mergeSession, fetchScore]
        Auth[authService.js<br/>login, register, logout, remove]
    end

    subgraph "CORE"
        App[App.js<br/>instancia de DOMmanager]
        Router[Router.js<br/>init y navigate]
    end

    subgraph "COMPONENTS"
        DOMmgr[DOMmanager.js<br/>createLayout, preloadAssets, setupRouter]
        NavBar[NavBar.js<br/>createBlocks, createButtons]
        Page[Page.js<br/>render y createBackground]
    end

    subgraph "PAGES"
        Pages[Content.js<br/>Pages registry]
        CatPage[CatPage.js<br/>renderCatPage]
        UserPage[UserPage.js<br/>renderUserPage, loggedIn, loggedOut]
    end

    subgraph "EXTERNAL API"
        CatAPI[TheCatAPI<br/>v1 images search]
    end

    App --> DOMmgr
    DOMmgr --> NavBar
    DOMmgr --> Router
    DOMmgr --> Pages
    DOMmgr --> Layout[Layout DOM<br/>header, nav, main, footer]

    Router --> Pages
    Router --> NavBar
    NavBar --> Router

    Pages --> Page
    Pages --> CatPage
    Pages --> UserPage

    Page --> BG[bg-media<br/>video o imagen]
    Page ---> PC[section.page-content]
    Page ---> PF[Page.fn renderContent]

    CatPage --> PF
    UserPage --> PF

    PF --> Storage
    PF --> Auth
    Auth --> Storage
    Storage --> Browser[localStorage]

    CatPage --> CatAPI

    Utils --> DOMmgr
    Utils --> NavBar
    Utils --> Page
    Utils --> CatPage
    Utils --> UserPage

    DataJS --> Utils
    DataJS --> Pages